# Generated by oh-my-posh
# Inserts the prompt command into Nushell

def create_left_prompt [] {
    oh-my-posh print primary --config 'M365Princess'
}

def create_right_prompt [] {
    oh-my-posh print secondary --config 'M365Princess'
}

let-env PROMPT_COMMAND = { create_left_prompt }
let-env PROMPT_COMMAND_RIGHT = { create_right_prompt }
